#!/usr/bin/env bash
# While Best School loop
#!/usr/bin/env bash
# While Best School loop
i=1

while [ $i -le 9 ]
do
  echo Best School
  ((i++))
	if [ $i = 10 ]
        then
                echo -e "Hi \nBest School"

       fi
done
