#!/usr/bin/env bash
# loops from 1 to 10
i=1

while [ $i -le 20 ]
do
  echo "$i"
  ((i++))
        case $i in
	5) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
        esac 
done
