#!/usr/bin/env bash
# loops from 1 to 10
i=1

while [ $i -le 20 ]
do
  echo "$i"
  ((i++))
        if  [ $i = 5 ]
                then echo "bad luck from China"
        elif [ $i = 9 ]
                then echo "bad luck from Japan"
        elif [ $i = 18 ]
		then echo "bad luck from Italy"
        fi
done
